environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765354544123
  identifier: NGPipeAutoNonMainEnvTi2nDtPUUa
  tags: {}
  name: NGPipeAutoNonMainEnvTi2nDtPUUa
  type: PreProduction
