environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763139226401
  identifier: NGPipeAutoEnv1763139226401
  tags: {}
  name: NGPipeAutoEnv1763139226401
  type: PreProduction
