environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767080321769
  identifier: NGPipeAutoNonMainEnvPKbnYp8mJj
  tags: {}
  name: NGPipeAutoNonMainEnvPKbnYp8mJj
  type: PreProduction
