environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768333617487
  identifier: NGPipeAutoNonMainEnvsjHdyArokD
  tags: {}
  name: NGPipeAutoNonMainEnvsjHdyArokD
  type: PreProduction
