environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764768192846
  identifier: NGPipeAutoEnv1764768192846
  tags: {}
  name: NGPipeAutoEnv1764768192846
  type: PreProduction
