environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769687764471
  identifier: NGPipeAutoEnv1769687764471
  tags: {}
  name: NGPipeAutoEnv1769687764471
  type: PreProduction
