environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764861514413
  identifier: NGPipeAutoEnv1764861514413
  tags: {}
  name: NGPipeAutoEnv1764861514413
  type: PreProduction
