environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765517636950
  identifier: NGPipeAutoEnv1765517636950
  tags: {}
  name: NGPipeAutoEnv1765517636950
  type: PreProduction
