environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766038597662
  identifier: NGPipeAutoNonMainEnvbSHJYNPG3m
  tags: {}
  name: NGPipeAutoNonMainEnvbSHJYNPG3m
  type: PreProduction
