environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763633646261
  identifier: NGPipeAutoNonMainEnvtCqWapCMim
  tags: {}
  name: NGPipeAutoNonMainEnvtCqWapCMim
  type: PreProduction
