environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762195924080
  identifier: NGPipeAutoNonMainEnvqmpFYy9xZ5
  tags: {}
  name: NGPipeAutoNonMainEnvqmpFYy9xZ5
  type: PreProduction
