environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765810900904
  identifier: NGPipeAutoEnv1765810900904
  tags: {}
  name: NGPipeAutoEnv1765810900904
  type: PreProduction
