environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768042759602
  identifier: NGPipeAutoNonMainEnvYiCN78Pgxn
  tags: {}
  name: NGPipeAutoNonMainEnvYiCN78Pgxn
  type: PreProduction
