environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765182604756
  identifier: NGPipeAutoEnv1765182604756
  tags: {}
  name: NGPipeAutoEnv1765182604756
  type: PreProduction
