environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764144878851
  identifier: NGPipeAutoNonMainEnvZiMoEBBA6W
  tags: {}
  name: NGPipeAutoNonMainEnvZiMoEBBA6W
  type: PreProduction
