environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764572558283
  identifier: NGPipeAutoNonMainEnv0xfvoZmt6k
  tags: {}
  name: NGPipeAutoNonMainEnv0xfvoZmt6k
  type: PreProduction
