environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767945262574
  identifier: NGPipeAutoNonMainEnvn19OZkyWnL
  tags: {}
  name: NGPipeAutoNonMainEnvn19OZkyWnL
  type: PreProduction
