environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763633646261
  identifier: NGPipeAutoEnv1763633646261
  tags: {}
  name: NGPipeAutoEnv1763633646261
  type: PreProduction
