environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764755546907
  identifier: NGPipeAutoNonMainEnvZPx03rUTQP
  tags: {}
  name: NGPipeAutoNonMainEnvZPx03rUTQP
  type: PreProduction
