environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769513472978
  identifier: NGPipeAutoEnv1769513472978
  tags: {}
  name: NGPipeAutoEnv1769513472978
  type: PreProduction
