environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762927325639
  identifier: NGPipeAutoEnv1762927325639
  tags: {}
  name: NGPipeAutoEnv1762927325639
  type: PreProduction
