environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768764376849
  identifier: NGPipeAutoNonMainEnvZ5FTL8Mj5N
  tags: {}
  name: NGPipeAutoNonMainEnvZ5FTL8Mj5N
  type: PreProduction
