environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762402626690
  identifier: NGPipeAutoEnv1762402626690
  tags: {}
  name: NGPipeAutoEnv1762402626690
  type: PreProduction
