environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769603310829
  identifier: NGPipeAutoEnv1769603310829
  tags: {}
  name: NGPipeAutoEnv1769603310829
  type: PreProduction
