environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763372042337
  identifier: NGPipeAutoNonMainEnv4Og8SZdMl7
  tags: {}
  name: NGPipeAutoNonMainEnv4Og8SZdMl7
  type: PreProduction
