environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765210251301
  identifier: NGPipeAutoEnv1765210251301
  tags: {}
  name: NGPipeAutoEnv1765210251301
  type: PreProduction
