environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762181147093
  identifier: NGPipeAutoNonMainEnvWUe1nYQctD
  tags: {}
  name: NGPipeAutoNonMainEnvWUe1nYQctD
  type: PreProduction
