environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764759528375
  identifier: NGPipeAutoEnv1764759528375
  tags: {}
  name: NGPipeAutoEnv1764759528375
  type: PreProduction
