environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762160394698
  identifier: NGPipeAutoNonMainEnv1cKHoRuKHU
  tags: {}
  name: NGPipeAutoNonMainEnv1cKHoRuKHU
  type: PreProduction
