environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762494350235
  identifier: NGPipeAutoNonMainEnvKZW8WTA8Gf
  tags: {}
  name: NGPipeAutoNonMainEnvKZW8WTA8Gf
  type: PreProduction
