environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763983325793
  identifier: NGPipeAutoNonMainEnvHIj8KuCgq0
  tags: {}
  name: NGPipeAutoNonMainEnvHIj8KuCgq0
  type: PreProduction
