environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766271418122
  identifier: NGPipeAutoNonMainEnvfI88tYcajm
  tags: {}
  name: NGPipeAutoNonMainEnvfI88tYcajm
  type: PreProduction
