environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763622524351
  identifier: NGPipeAutoNonMainEnvubz8jX1BHA
  tags: {}
  name: NGPipeAutoNonMainEnvubz8jX1BHA
  type: PreProduction
