environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763044945250
  identifier: NGPipeAutoNonMainEnvILeSRxYXsK
  tags: {}
  name: NGPipeAutoNonMainEnvILeSRxYXsK
  type: PreProduction
