environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763185542126
  identifier: NGPipeAutoEnv1763185542126
  tags: {}
  name: NGPipeAutoEnv1763185542126
  type: PreProduction
