environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768825565800
  identifier: NGPipeAutoEnv1768825565800
  tags: {}
  name: NGPipeAutoEnv1768825565800
  type: PreProduction
