environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766951989981
  identifier: NGPipeAutoNonMainEnvTsgHWoIxql
  tags: {}
  name: NGPipeAutoNonMainEnvTsgHWoIxql
  type: PreProduction
