environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763027890785
  identifier: NGPipeAutoNonMainEnvqnOTFQpeQj
  tags: {}
  name: NGPipeAutoNonMainEnvqnOTFQpeQj
  type: PreProduction
