environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769656516873
  identifier: NGPipeAutoNonMainEnvWDqiiqdTvp
  tags: {}
  name: NGPipeAutoNonMainEnvWDqiiqdTvp
  type: PreProduction
