environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767081182074
  identifier: NGPipeAutoNonMainEnvxNiiuxaWyD
  tags: {}
  name: NGPipeAutoNonMainEnvxNiiuxaWyD
  type: PreProduction
