environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763060142817
  identifier: NGPipeAutoNonMainEnv5ubYe9CfCW
  tags: {}
  name: NGPipeAutoNonMainEnv5ubYe9CfCW
  type: PreProduction
