environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764572558283
  identifier: NGPipeAutoEnv1764572558283
  tags: {}
  name: NGPipeAutoEnv1764572558283
  type: PreProduction
