environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768161295255
  identifier: NGPipeAutoNonMainEnvXaXA3byzWH
  tags: {}
  name: NGPipeAutoNonMainEnvXaXA3byzWH
  type: PreProduction
