environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769577156630
  identifier: NGPipeAutoEnv1769577156630
  tags: {}
  name: NGPipeAutoEnv1769577156630
  type: PreProduction
