environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767933695758
  identifier: NGPipeAutoNonMainEnv1VJaXOgpAF
  tags: {}
  name: NGPipeAutoNonMainEnv1VJaXOgpAF
  type: PreProduction
