environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765365299461
  identifier: NGPipeAutoNonMainEnvdYbfQIXMoK
  tags: {}
  name: NGPipeAutoNonMainEnvdYbfQIXMoK
  type: PreProduction
