environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768248455648
  identifier: NGPipeAutoEnv1768248455648
  tags: {}
  name: NGPipeAutoEnv1768248455648
  type: PreProduction
