environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764754724161
  identifier: NGPipeAutoEnv1764754724161
  tags: {}
  name: NGPipeAutoEnv1764754724161
  type: PreProduction
