environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765214323871
  identifier: NGPipeAutoEnv1765214323871
  tags: {}
  name: NGPipeAutoEnv1765214323871
  type: PreProduction
