environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762179135937
  identifier: NGPipeAutoNonMainEnvII3Z9YBQKS
  tags: {}
  name: NGPipeAutoNonMainEnvII3Z9YBQKS
  type: PreProduction
