environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763605555463
  identifier: NGPipeAutoNonMainEnv6e5lcB4RQx
  tags: {}
  name: NGPipeAutoNonMainEnv6e5lcB4RQx
  type: PreProduction
