environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763060142817
  identifier: NGPipeAutoEnv1763060142817
  tags: {}
  name: NGPipeAutoEnv1763060142817
  type: PreProduction
