environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766472226269
  identifier: NGPipeAutoEnv1766472226269
  tags: {}
  name: NGPipeAutoEnv1766472226269
  type: PreProduction
