environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762178282233
  identifier: NGPipeAutoNonMainEnvp0FVt3RXwb
  tags: {}
  name: NGPipeAutoNonMainEnvp0FVt3RXwb
  type: PreProduction
