environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765353972743
  identifier: NGPipeAutoEnv1765353972743
  tags: {}
  name: NGPipeAutoEnv1765353972743
  type: PreProduction
