environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769065280316
  identifier: NGPipeAutoEnv1769065280316
  tags: {}
  name: NGPipeAutoEnv1769065280316
  type: PreProduction
