environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763639999221
  identifier: NGPipeAutoNonMainEnv1ZVVMXYm0l
  tags: {}
  name: NGPipeAutoNonMainEnv1ZVVMXYm0l
  type: PreProduction
