environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762215339450
  identifier: NGPipeAutoEnv1762215339450
  tags: {}
  name: NGPipeAutoEnv1762215339450
  type: PreProduction
