environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764066400451
  identifier: NGPipeAutoEnv1764066400451
  tags: {}
  name: NGPipeAutoEnv1764066400451
  type: PreProduction
