environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763185542126
  identifier: NGPipeAutoNonMainEnvoHYtp0hCsp
  tags: {}
  name: NGPipeAutoNonMainEnvoHYtp0hCsp
  type: PreProduction
