environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767734956084
  identifier: NGPipeAutoEnv1767734956084
  tags: {}
  name: NGPipeAutoEnv1767734956084
  type: PreProduction
