environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765353972743
  identifier: NGPipeAutoNonMainEnvCmK0AO1Wsx
  tags: {}
  name: NGPipeAutoNonMainEnvCmK0AO1Wsx
  type: PreProduction
