environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762195924080
  identifier: NGPipeAutoEnv1762195924080
  tags: {}
  name: NGPipeAutoEnv1762195924080
  type: PreProduction
