environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763372042337
  identifier: NGPipeAutoEnv1763372042337
  tags: {}
  name: NGPipeAutoEnv1763372042337
  type: PreProduction
