environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762163534820
  identifier: NGPipeAutoNonMainEnvpEjJU8oYML
  tags: {}
  name: NGPipeAutoNonMainEnvpEjJU8oYML
  type: PreProduction
