environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768970205741
  identifier: NGPipeAutoEnv1768970205741
  tags: {}
  name: NGPipeAutoEnv1768970205741
  type: PreProduction
