environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764066400451
  identifier: NGPipeAutoNonMainEnvQY5WgHXmII
  tags: {}
  name: NGPipeAutoNonMainEnvQY5WgHXmII
  type: PreProduction
