environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763640773646
  identifier: NGPipeAutoNonMainEnvSaoLK50wVh
  tags: {}
  name: NGPipeAutoNonMainEnvSaoLK50wVh
  type: PreProduction
