environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767851623989
  identifier: NGPipeAutoNonMainEnvsRcP5t68D8
  tags: {}
  name: NGPipeAutoNonMainEnvsRcP5t68D8
  type: PreProduction
