environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762952181125
  identifier: NGPipeAutoNonMainEnvAAEP7lPSOm
  tags: {}
  name: NGPipeAutoNonMainEnvAAEP7lPSOm
  type: PreProduction
