environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765912918497
  identifier: NGPipeAutoEnv1765912918497
  tags: {}
  name: NGPipeAutoEnv1765912918497
  type: PreProduction
