environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763225529323
  identifier: NGPipeAutoEnv1763225529323
  tags: {}
  name: NGPipeAutoEnv1763225529323
  type: PreProduction
