environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769577156630
  identifier: NGPipeAutoNonMainEnvIVs0QaMEqG
  tags: {}
  name: NGPipeAutoNonMainEnvIVs0QaMEqG
  type: PreProduction
