environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769603850426
  identifier: NGPipeAutoEnv1769603850426
  tags: {}
  name: NGPipeAutoEnv1769603850426
  type: PreProduction
