environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766472226269
  identifier: NGPipeAutoNonMainEnv4TrwIUuHME
  tags: {}
  name: NGPipeAutoNonMainEnv4TrwIUuHME
  type: PreProduction
