environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765524787408
  identifier: NGPipeAutoNonMainEnvc6DmdQxQK3
  tags: {}
  name: NGPipeAutoNonMainEnvc6DmdQxQK3
  type: PreProduction
