environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765171417044
  identifier: NGPipeAutoNonMainEnvViFkCKVtrJ
  tags: {}
  name: NGPipeAutoNonMainEnvViFkCKVtrJ
  type: PreProduction
