environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767955817877
  identifier: NGPipeAutoNonMainEnvLXRX1a2LGq
  tags: {}
  name: NGPipeAutoNonMainEnvLXRX1a2LGq
  type: PreProduction
