environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762160201151
  identifier: NGPipeAutoNonMainEnvaOQCvlg6L1
  tags: {}
  name: NGPipeAutoNonMainEnvaOQCvlg6L1
  type: PreProduction
