environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763044214868
  identifier: NGPipeAutoEnv1763044214868
  tags: {}
  name: NGPipeAutoEnv1763044214868
  type: PreProduction
