environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763630344066
  identifier: NGPipeAutoNonMainEnvkea8jtGkdu
  tags: {}
  name: NGPipeAutoNonMainEnvkea8jtGkdu
  type: PreProduction
