environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763620918269
  identifier: NGPipeAutoEnv1763620918269
  tags: {}
  name: NGPipeAutoEnv1763620918269
  type: PreProduction
