environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763622967966
  identifier: NGPipeAutoNonMainEnv8qQGt74lMN
  tags: {}
  name: NGPipeAutoNonMainEnv8qQGt74lMN
  type: PreProduction
