environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765351129953
  identifier: NGPipeAutoNonMainEnvwfRr17WMu2
  tags: {}
  name: NGPipeAutoNonMainEnvwfRr17WMu2
  type: PreProduction
