environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763639999221
  identifier: NGPipeAutoEnv1763639999221
  tags: {}
  name: NGPipeAutoEnv1763639999221
  type: PreProduction
