environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769143274678
  identifier: NGPipeAutoEnv1769143274678
  tags: {}
  name: NGPipeAutoEnv1769143274678
  type: PreProduction
