environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762161013330
  identifier: NGPipeAutoNonMainEnvOUbJMaFdH7
  tags: {}
  name: NGPipeAutoNonMainEnvOUbJMaFdH7
  type: PreProduction
