environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764803789066
  identifier: NGPipeAutoEnv1764803789066
  tags: {}
  name: NGPipeAutoEnv1764803789066
  type: PreProduction
