environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764844613382
  identifier: NGPipeAutoNonMainEnvUIPQc7L93s
  tags: {}
  name: NGPipeAutoNonMainEnvUIPQc7L93s
  type: PreProduction
