environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763983325793
  identifier: NGPipeAutoEnv1763983325793
  tags: {}
  name: NGPipeAutoEnv1763983325793
  type: PreProduction
