environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764228643527
  identifier: NGPipeAutoNonMainEnvjqSwVH773R
  tags: {}
  name: NGPipeAutoNonMainEnvjqSwVH773R
  type: PreProduction
