environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768042759602
  identifier: NGPipeAutoEnv1768042759602
  tags: {}
  name: NGPipeAutoEnv1768042759602
  type: PreProduction
