environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765434405162
  identifier: NGPipeAutoNonMainEnvyusSJViUhT
  tags: {}
  name: NGPipeAutoNonMainEnvyusSJViUhT
  type: PreProduction
