environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767804698979
  identifier: NGPipeAutoNonMainEnvJaHesqCFBd
  tags: {}
  name: NGPipeAutoNonMainEnvJaHesqCFBd
  type: PreProduction
