environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762181740198
  identifier: NGPipeAutoEnv1762181740198
  tags: {}
  name: NGPipeAutoEnv1762181740198
  type: PreProduction
