environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766951989981
  identifier: NGPipeAutoEnv1766951989981
  tags: {}
  name: NGPipeAutoEnv1766951989981
  type: PreProduction
