environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769679297402
  identifier: NGPipeAutoNonMainEnvvregzVSvvr
  tags: {}
  name: NGPipeAutoNonMainEnvvregzVSvvr
  type: PreProduction
