environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762181365300
  identifier: NGPipeAutoNonMainEnv2aq2dEXynR
  tags: {}
  name: NGPipeAutoNonMainEnv2aq2dEXynR
  type: PreProduction
