environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763538796973
  identifier: NGPipeAutoNonMainEnvKYUZ9yCE5n
  tags: {}
  name: NGPipeAutoNonMainEnvKYUZ9yCE5n
  type: PreProduction
