environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765912342580
  identifier: NGPipeAutoNonMainEnvbTRUStlSiC
  tags: {}
  name: NGPipeAutoNonMainEnvbTRUStlSiC
  type: PreProduction
