environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768825213600
  identifier: NGPipeAutoNonMainEnvNP1HLNmggU
  tags: {}
  name: NGPipeAutoNonMainEnvNP1HLNmggU
  type: PreProduction
