environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763620918269
  identifier: NGPipeAutoNonMainEnv5RCxS3OrO3
  tags: {}
  name: NGPipeAutoNonMainEnv5RCxS3OrO3
  type: PreProduction
