environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764225709260
  identifier: NGPipeAutoEnv1764225709260
  tags: {}
  name: NGPipeAutoEnv1764225709260
  type: PreProduction
