environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762402022916
  identifier: NGPipeAutoNonMainEnvP9JAQjwGc8
  tags: {}
  name: NGPipeAutoNonMainEnvP9JAQjwGc8
  type: PreProduction
