environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764145605978
  identifier: NGPipeAutoNonMainEnvwk8FqI2cUT
  tags: {}
  name: NGPipeAutoNonMainEnvwk8FqI2cUT
  type: PreProduction
