environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765433412553
  identifier: NGPipeAutoEnv1765433412553
  tags: {}
  name: NGPipeAutoEnv1765433412553
  type: PreProduction
