environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765213440559
  identifier: NGPipeAutoEnv1765213440559
  tags: {}
  name: NGPipeAutoEnv1765213440559
  type: PreProduction
