environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763629863849
  identifier: NGPipeAutoNonMainEnvrWgMQ1dJnP
  tags: {}
  name: NGPipeAutoNonMainEnvrWgMQ1dJnP
  type: PreProduction
