environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764754724161
  identifier: NGPipeAutoNonMainEnv9NctMub2HN
  tags: {}
  name: NGPipeAutoNonMainEnv9NctMub2HN
  type: PreProduction
