environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769458920904
  identifier: NGPipeAutoEnv1769458920904
  tags: {}
  name: NGPipeAutoEnv1769458920904
  type: PreProduction
