environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766377423520
  identifier: NGPipeAutoEnv1766377423520
  tags: {}
  name: NGPipeAutoEnv1766377423520
  type: PreProduction
