environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762927325639
  identifier: NGPipeAutoNonMainEnvHPTKLITGMq
  tags: {}
  name: NGPipeAutoNonMainEnvHPTKLITGMq
  type: PreProduction
