environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765810900904
  identifier: NGPipeAutoNonMainEnvdrE42DfDJB
  tags: {}
  name: NGPipeAutoNonMainEnvdrE42DfDJB
  type: PreProduction
