environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769788190325
  identifier: NGPipeAutoNonMainEnvN1PtlMTkHH
  tags: {}
  name: NGPipeAutoNonMainEnvN1PtlMTkHH
  type: PreProduction
