environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763028814982
  identifier: NGPipeAutoEnv1763028814982
  tags: {}
  name: NGPipeAutoEnv1763028814982
  type: PreProduction
