environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762181740198
  identifier: NGPipeAutoNonMainEnviDTzjhlFn1
  tags: {}
  name: NGPipeAutoNonMainEnviDTzjhlFn1
  type: PreProduction
