environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763634074849
  identifier: NGPipeAutoNonMainEnvNrb8p6xJYC
  tags: {}
  name: NGPipeAutoNonMainEnvNrb8p6xJYC
  type: PreProduction
