environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763028215424
  identifier: NGPipeAutoNonMainEnvz7JjDv6RzO
  tags: {}
  name: NGPipeAutoNonMainEnvz7JjDv6RzO
  type: PreProduction
