environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762940989037
  identifier: NGPipeAutoNonMainEnvqJUi5hFWcA
  tags: {}
  name: NGPipeAutoNonMainEnvqJUi5hFWcA
  type: PreProduction
