environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768767747027
  identifier: NGPipeAutoNonMainEnvbhTnfzyGS0
  tags: {}
  name: NGPipeAutoNonMainEnvbhTnfzyGS0
  type: PreProduction
