environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769620232336
  identifier: NGPipeAutoEnv1769620232336
  tags: {}
  name: NGPipeAutoEnv1769620232336
  type: PreProduction
