environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764768192846
  identifier: NGPipeAutoNonMainEnv4BO2rfqGtd
  tags: {}
  name: NGPipeAutoNonMainEnv4BO2rfqGtd
  type: PreProduction
