environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767584829140
  identifier: NGPipeAutoEnv1767584829140
  tags: {}
  name: NGPipeAutoEnv1767584829140
  type: PreProduction
