environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764572355084
  identifier: NGPipeAutoNonMainEnvQ8WMppSrhA
  tags: {}
  name: NGPipeAutoNonMainEnvQ8WMppSrhA
  type: PreProduction
