environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765804585353
  identifier: NGPipeAutoNonMainEnvnuDAIk76U2
  tags: {}
  name: NGPipeAutoNonMainEnvnuDAIk76U2
  type: PreProduction
