environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765351850876
  identifier: NGPipeAutoEnv1765351850876
  tags: {}
  name: NGPipeAutoEnv1765351850876
  type: PreProduction
