environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763538796973
  identifier: NGPipeAutoEnv1763538796973
  tags: {}
  name: NGPipeAutoEnv1763538796973
  type: PreProduction
