environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769513909699
  identifier: NGPipeAutoEnv1769513909699
  tags: {}
  name: NGPipeAutoEnv1769513909699
  type: PreProduction
