environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767852468914
  identifier: NGPipeAutoNonMainEnvhDHo2Brkih
  tags: {}
  name: NGPipeAutoNonMainEnvhDHo2Brkih
  type: PreProduction
