environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767851623989
  identifier: NGPipeAutoEnv1767851623989
  tags: {}
  name: NGPipeAutoEnv1767851623989
  type: PreProduction
