environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764571826149
  identifier: NGPipeAutoEnv1764571826149
  tags: {}
  name: NGPipeAutoEnv1764571826149
  type: PreProduction
