environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762847383754
  identifier: NGPipeAutoEnv1762847383754
  tags: {}
  name: NGPipeAutoEnv1762847383754
  type: PreProduction
