environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765352594739
  identifier: NGPipeAutoEnv1765352594739
  tags: {}
  name: NGPipeAutoEnv1765352594739
  type: PreProduction
