environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762941560035
  identifier: NGPipeAutoNonMainEnvtah7W9YwxG
  tags: {}
  name: NGPipeAutoNonMainEnvtah7W9YwxG
  type: PreProduction
