environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767736752577
  identifier: NGPipeAutoNonMainEnv17BtCkWtGD
  tags: {}
  name: NGPipeAutoNonMainEnv17BtCkWtGD
  type: PreProduction
