environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769679297402
  identifier: NGPipeAutoEnv1769679297402
  tags: {}
  name: NGPipeAutoEnv1769679297402
  type: PreProduction
