environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768043285209
  identifier: NGPipeAutoNonMainEnvaUOwtTZxg3
  tags: {}
  name: NGPipeAutoNonMainEnvaUOwtTZxg3
  type: PreProduction
