environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764572355084
  identifier: NGPipeAutoEnv1764572355084
  tags: {}
  name: NGPipeAutoEnv1764572355084
  type: PreProduction
