environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765882797862
  identifier: NGPipeAutoNonMainEnvxmgWO2VWha
  tags: {}
  name: NGPipeAutoNonMainEnvxmgWO2VWha
  type: PreProduction
