environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765354963935
  identifier: NGPipeAutoNonMainEnv6LgZaKGAVJ
  tags: {}
  name: NGPipeAutoNonMainEnv6LgZaKGAVJ
  type: PreProduction
