environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769610045306
  identifier: NGPipeAutoNonMainEnvQtfEAc7BPA
  tags: {}
  name: NGPipeAutoNonMainEnvQtfEAc7BPA
  type: PreProduction
