environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767080321769
  identifier: NGPipeAutoEnv1767080321769
  tags: {}
  name: NGPipeAutoEnv1767080321769
  type: PreProduction
