environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769620232336
  identifier: NGPipeAutoNonMainEnvFBio74toc5
  tags: {}
  name: NGPipeAutoNonMainEnvFBio74toc5
  type: PreProduction
