environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765182604756
  identifier: NGPipeAutoNonMainEnv1pQvXG0xvL
  tags: {}
  name: NGPipeAutoNonMainEnv1pQvXG0xvL
  type: PreProduction
