environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762951511496
  identifier: NGPipeAutoNonMainEnv4syovcdZC5
  tags: {}
  name: NGPipeAutoNonMainEnv4syovcdZC5
  type: PreProduction
