environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766271418122
  identifier: NGPipeAutoEnv1766271418122
  tags: {}
  name: NGPipeAutoEnv1766271418122
  type: PreProduction
