environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762160750338
  identifier: NGPipeAutoNonMainEnvpgPJnl9dLa
  tags: {}
  name: NGPipeAutoNonMainEnvpgPJnl9dLa
  type: PreProduction
