environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762160040864
  identifier: NGPipeAutoEnv1762160040864
  tags: {}
  name: NGPipeAutoEnv1762160040864
  type: PreProduction
