environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768161295255
  identifier: NGPipeAutoEnv1768161295255
  tags: {}
  name: NGPipeAutoEnv1768161295255
  type: PreProduction
