environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769751253010
  identifier: NGPipeAutoNonMainEnvBIoA0ceMJ0
  tags: {}
  name: NGPipeAutoNonMainEnvBIoA0ceMJ0
  type: PreProduction
