environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763028717326
  identifier: NGPipeAutoNonMainEnvDQZOHKgxRd
  tags: {}
  name: NGPipeAutoNonMainEnvDQZOHKgxRd
  type: PreProduction
