environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763640434845
  identifier: NGPipeAutoNonMainEnv3ppVaS6lmB
  tags: {}
  name: NGPipeAutoNonMainEnv3ppVaS6lmB
  type: PreProduction
