environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763139226401
  identifier: NGPipeAutoNonMainEnvvHqym2mcKA
  tags: {}
  name: NGPipeAutoNonMainEnvvHqym2mcKA
  type: PreProduction
