environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768825565800
  identifier: NGPipeAutoNonMainEnvpLy9ZefGXw
  tags: {}
  name: NGPipeAutoNonMainEnvpLy9ZefGXw
  type: PreProduction
