environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768380417990
  identifier: NGPipeAutoNonMainEnvg0Em4AcI3R
  tags: {}
  name: NGPipeAutoNonMainEnvg0Em4AcI3R
  type: PreProduction
