environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765352847248
  identifier: NGPipeAutoEnv1765352847248
  tags: {}
  name: NGPipeAutoEnv1765352847248
  type: PreProduction
