environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763634373951
  identifier: NGPipeAutoNonMainEnvqytrkqrXK4
  tags: {}
  name: NGPipeAutoNonMainEnvqytrkqrXK4
  type: PreProduction
