environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768831523462
  identifier: NGPipeAutoNonMainEnvCMgNFqY1r5
  tags: {}
  name: NGPipeAutoNonMainEnvCMgNFqY1r5
  type: PreProduction
