environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766046381718
  identifier: NGPipeAutoNonMainEnvQp1TeEzmyD
  tags: {}
  name: NGPipeAutoNonMainEnvQp1TeEzmyD
  type: PreProduction
