environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765352847248
  identifier: NGPipeAutoNonMainEnv0X7LVnfqZI
  tags: {}
  name: NGPipeAutoNonMainEnv0X7LVnfqZI
  type: PreProduction
