environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765170802135
  identifier: NGPipeAutoEnv1765170802135
  tags: {}
  name: NGPipeAutoEnv1765170802135
  type: PreProduction
