environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764144878851
  identifier: NGPipeAutoEnv1764144878851
  tags: {}
  name: NGPipeAutoEnv1764144878851
  type: PreProduction
