environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765213440559
  identifier: NGPipeAutoNonMainEnvZr7DIQozFU
  tags: {}
  name: NGPipeAutoNonMainEnvZr7DIQozFU
  type: PreProduction
