environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763623269564
  identifier: NGPipeAutoNonMainEnvNu0jsaj0Q9
  tags: {}
  name: NGPipeAutoNonMainEnvNu0jsaj0Q9
  type: PreProduction
