environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768831523462
  identifier: NGPipeAutoEnv1768831523462
  tags: {}
  name: NGPipeAutoEnv1768831523462
  type: PreProduction
