environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762179229018
  identifier: NGPipeAutoNonMainEnvG0CXP4Qujk
  tags: {}
  name: NGPipeAutoNonMainEnvG0CXP4Qujk
  type: PreProduction
