environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762402022916
  identifier: NGPipeAutoEnv1762402022916
  tags: {}
  name: NGPipeAutoEnv1762402022916
  type: PreProduction
