environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769513472978
  identifier: NGPipeAutoNonMainEnvi2JknNrJH1
  tags: {}
  name: NGPipeAutoNonMainEnvi2JknNrJH1
  type: PreProduction
