environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765805113471
  identifier: NGPipeAutoNonMainEnvWJxmWu6Cs6
  tags: {}
  name: NGPipeAutoNonMainEnvWJxmWu6Cs6
  type: PreProduction
