environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769544320051
  identifier: NGPipeAutoEnv1769544320051
  tags: {}
  name: NGPipeAutoEnv1769544320051
  type: PreProduction
