environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762848680722
  identifier: NGPipeAutoEnv1762848680722
  tags: {}
  name: NGPipeAutoEnv1762848680722
  type: PreProduction
