environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763622011001
  identifier: NGPipeAutoNonMainEnv6FFd2Oze5m
  tags: {}
  name: NGPipeAutoNonMainEnv6FFd2Oze5m
  type: PreProduction
