environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763357990060
  identifier: NGPipeAutoNonMainEnvt0h8E4oFal
  tags: {}
  name: NGPipeAutoNonMainEnvt0h8E4oFal
  type: PreProduction
