environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765214323871
  identifier: NGPipeAutoNonMainEnvRcRLHhFrzK
  tags: {}
  name: NGPipeAutoNonMainEnvRcRLHhFrzK
  type: PreProduction
