environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762891563355
  identifier: NGPipeAutoEnv1762891563355
  tags: {}
  name: NGPipeAutoEnv1762891563355
  type: PreProduction
