environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762514017522
  identifier: NGPipeAutoNonMainEnvOV23xHk3W0
  tags: {}
  name: NGPipeAutoNonMainEnvOV23xHk3W0
  type: PreProduction
