environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769788190325
  identifier: NGPipeAutoEnv1769788190325
  tags: {}
  name: NGPipeAutoEnv1769788190325
  type: PreProduction
