environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768248455648
  identifier: NGPipeAutoNonMainEnv7n7euBXiDY
  tags: {}
  name: NGPipeAutoNonMainEnv7n7euBXiDY
  type: PreProduction
