environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764227817264
  identifier: NGPipeAutoNonMainEnvzruzvykujK
  tags: {}
  name: NGPipeAutoNonMainEnvzruzvykujK
  type: PreProduction
