environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767933695758
  identifier: NGPipeAutoEnv1767933695758
  tags: {}
  name: NGPipeAutoEnv1767933695758
  type: PreProduction
