environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763605555463
  identifier: NGPipeAutoEnv1763605555463
  tags: {}
  name: NGPipeAutoEnv1763605555463
  type: PreProduction
