environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769493354339
  identifier: NGPipeAutoEnv1769493354339
  tags: {}
  name: NGPipeAutoEnv1769493354339
  type: PreProduction
