environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762945284002
  identifier: NGPipeAutoEnv1762945284002
  tags: {}
  name: NGPipeAutoEnv1762945284002
  type: PreProduction
