environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762941887334
  identifier: NGPipeAutoNonMainEnvt5kkw2LtmL
  tags: {}
  name: NGPipeAutoNonMainEnvt5kkw2LtmL
  type: PreProduction
