environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762159904096
  identifier: NGPipeAutoEnv176215990409
  tags: {}
  name: NGPipeAutoEnv1762159904096
  type: PreProduction
