environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764350875122
  identifier: NGPipeAutoEnv1764350875122
  tags: {}
  name: NGPipeAutoEnv1764350875122
  type: PreProduction
