environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768970205741
  identifier: NGPipeAutoNonMainEnvV5aiwTmDHX
  tags: {}
  name: NGPipeAutoNonMainEnvV5aiwTmDHX
  type: PreProduction
