environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763545592300
  identifier: NGPipeAutoEnv1763545592300
  tags: {}
  name: NGPipeAutoEnv1763545592300
  type: PreProduction
