environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762495160327
  identifier: NGPipeAutoNonMainEnvWVtTecgk38
  tags: {}
  name: NGPipeAutoNonMainEnvWVtTecgk38
  type: PreProduction
