environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762957713229
  identifier: NGPipeAutoNonMainEnvSLTShVq0kz
  tags: {}
  name: NGPipeAutoNonMainEnvSLTShVq0kz
  type: PreProduction
