environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762216001262
  identifier: NGPipeAutoNonMainEnvvByBS0qgpg
  tags: {}
  name: NGPipeAutoNonMainEnvvByBS0qgpg
  type: PreProduction
