environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768397358326
  identifier: NGPipeAutoEnv1768397358326
  tags: {}
  name: NGPipeAutoEnv1768397358326
  type: PreProduction
