environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767872771942
  identifier: NGPipeAutoEnv1767872771942
  tags: {}
  name: NGPipeAutoEnv1767872771942
  type: PreProduction
