environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769687764471
  identifier: NGPipeAutoNonMainEnvollOUw7mvn
  tags: {}
  name: NGPipeAutoNonMainEnvollOUw7mvn
  type: PreProduction
