environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762160539228
  identifier: NGPipeAutoNonMainEnv0fBGlj9kXM
  tags: {}
  name: NGPipeAutoNonMainEnv0fBGlj9kXM
  type: PreProduction
