environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763225529323
  identifier: NGPipeAutoNonMainEnv8QVNpJxsId
  tags: {}
  name: NGPipeAutoNonMainEnv8QVNpJxsId
  type: PreProduction
