environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764759528375
  identifier: NGPipeAutoNonMainEnvmMTIeSTsid
  tags: {}
  name: NGPipeAutoNonMainEnvmMTIeSTsid
  type: PreProduction
