environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762847383754
  identifier: NGPipeAutoNonMainEnv3qjuMpJwM9
  tags: {}
  name: NGPipeAutoNonMainEnv3qjuMpJwM9
  type: PreProduction
