environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764844613382
  identifier: NGPipeAutoEnv1764844613382
  tags: {}
  name: NGPipeAutoEnv1764844613382
  type: PreProduction
