environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764580568711
  identifier: NGPipeAutoNonMainEnvk0oEdXTqMZ
  tags: {}
  name: NGPipeAutoNonMainEnvk0oEdXTqMZ
  type: PreProduction
