environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765517636950
  identifier: NGPipeAutoNonMainEnv8QSZQH283D
  tags: {}
  name: NGPipeAutoNonMainEnv8QSZQH283D
  type: PreProduction
