environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763027890785
  identifier: NGPipeAutoEnv1763027890785
  tags: {}
  name: NGPipeAutoEnv1763027890785
  type: PreProduction
