environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762951511496
  identifier: NGPipeAutoEnv1762951511496
  tags: {}
  name: NGPipeAutoEnv1762951511496
  type: PreProduction
