environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764407252598
  identifier: NGPipeAutoEnv1764407252598
  tags: {}
  name: NGPipeAutoEnv1764407252598
  type: PreProduction
