environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764755279559
  identifier: NGPipeAutoNonMainEnv1MnL21GPgc
  tags: {}
  name: NGPipeAutoNonMainEnv1MnL21GPgc
  type: PreProduction
