environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767080860576
  identifier: NGPipeAutoNonMainEnvLbeYOHKuOI
  tags: {}
  name: NGPipeAutoNonMainEnvLbeYOHKuOI
  type: PreProduction
