environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765433920962
  identifier: NGPipeAutoNonMainEnvK9vch3cV3w
  tags: {}
  name: NGPipeAutoNonMainEnvK9vch3cV3w
  type: PreProduction
