environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763629863849
  identifier: NGPipeAutoEnv1763629863849
  tags: {}
  name: NGPipeAutoEnv1763629863849
  type: PreProduction
