environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768767747027
  identifier: NGPipeAutoEnv1768767747027
  tags: {}
  name: NGPipeAutoEnv1768767747027
  type: PreProduction
