environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767945262574
  identifier: NGPipeAutoEnv1767945262574
  tags: {}
  name: NGPipeAutoEnv1767945262574
  type: PreProduction
