environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765804585353
  identifier: NGPipeAutoEnv1765804585353
  tags: {}
  name: NGPipeAutoEnv1765804585353
  type: PreProduction
