environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762494856626
  identifier: NGPipeAutoNonMainEnvGXNdysWzGb
  tags: {}
  name: NGPipeAutoNonMainEnvGXNdysWzGb
  type: PreProduction
