environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762957052388
  identifier: NGPipeAutoEnv1762957052388
  tags: {}
  name: NGPipeAutoEnv1762957052388
  type: PreProduction
