environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763545592300
  identifier: NGPipeAutoNonMainEnvi1ExpZ1olt
  tags: {}
  name: NGPipeAutoNonMainEnvi1ExpZ1olt
  type: PreProduction
