environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767085444515
  identifier: NGPipeAutoNonMainEnvklepiMchbg
  tags: {}
  name: NGPipeAutoNonMainEnvklepiMchbg
  type: PreProduction
