environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762163332619
  identifier: NGPipeAutoNonMainEnvINOpBZU4pd
  tags: {}
  name: NGPipeAutoNonMainEnvINOpBZU4pd
  type: PreProduction
