environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768397358326
  identifier: NGPipeAutoNonMainEnvzusmDjPYMO
  tags: {}
  name: NGPipeAutoNonMainEnvzusmDjPYMO
  type: PreProduction
