environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763982579511
  identifier: NGPipeAutoNonMainEnvJ0KDgGIGOc
  tags: {}
  name: NGPipeAutoNonMainEnvJ0KDgGIGOc
  type: PreProduction
