environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762890648473
  identifier: NGPipeAutoNonMainEnvjFAkuBgWV8
  tags: {}
  name: NGPipeAutoNonMainEnvjFAkuBgWV8
  type: PreProduction
