environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762940989037
  identifier: NGPipeAutoEnv1762940989037
  tags: {}
  name: NGPipeAutoEnv1762940989037
  type: PreProduction
