environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764225709260
  identifier: NGPipeAutoNonMainEnvNcPtqrXbHr
  tags: {}
  name: NGPipeAutoNonMainEnvNcPtqrXbHr
  type: PreProduction
