environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762494350235
  identifier: NGPipeAutoEnv1762494350235
  tags: {}
  name: NGPipeAutoEnv1762494350235
  type: PreProduction
