environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764407252598
  identifier: NGPipeAutoNonMainEnvbeYC1xGbGa
  tags: {}
  name: NGPipeAutoNonMainEnvbeYC1xGbGa
  type: PreProduction
