environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765354917033
  identifier: NGPipeAutoNonMainEnvxDyOvH7VPf
  tags: {}
  name: NGPipeAutoNonMainEnvxDyOvH7VPf
  type: PreProduction
