environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769065280316
  identifier: NGPipeAutoNonMainEnv1HlnJGTb8j
  tags: {}
  name: NGPipeAutoNonMainEnv1HlnJGTb8j
  type: PreProduction
