environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765354917033
  identifier: NGPipeAutoEnv1765354917033
  tags: {}
  name: NGPipeAutoEnv1765354917033
  type: PreProduction
