environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768764376849
  identifier: NGPipeAutoEnv1768764376849
  tags: {}
  name: NGPipeAutoEnv1768764376849
  type: PreProduction
