environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764803789066
  identifier: NGPipeAutoNonMainEnvsYWZ1c8Km0
  tags: {}
  name: NGPipeAutoNonMainEnvsYWZ1c8Km0
  type: PreProduction
