environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762752173244
  identifier: NGPipeAutoEnv1762752173244
  tags: {}
  name: NGPipeAutoEnv1762752173244
  type: PreProduction
