environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769633691277
  identifier: NGPipeAutoEnv1769633691277
  tags: {}
  name: NGPipeAutoEnv1769633691277
  type: PreProduction
