environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764228643527
  identifier: NGPipeAutoEnv1764228643527
  tags: {}
  name: NGPipeAutoEnv1764228643527
  type: PreProduction
