environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762848680722
  identifier: NGPipeAutoNonMainEnv5Yxb3n13fz
  tags: {}
  name: NGPipeAutoNonMainEnv5Yxb3n13fz
  type: PreProduction
