environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769603850426
  identifier: NGPipeAutoNonMainEnvI0W5biYijV
  tags: {}
  name: NGPipeAutoNonMainEnvI0W5biYijV
  type: PreProduction
