environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769544320051
  identifier: NGPipeAutoNonMainEnvbXHqrGkSNi
  tags: {}
  name: NGPipeAutoNonMainEnvbXHqrGkSNi
  type: PreProduction
