environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769751253010
  identifier: NGPipeAutoEnv1769751253010
  tags: {}
  name: NGPipeAutoEnv1769751253010
  type: PreProduction
