environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765433412553
  identifier: NGPipeAutoNonMainEnv6olJNhnY33
  tags: {}
  name: NGPipeAutoNonMainEnv6olJNhnY33
  type: PreProduction
