environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763963343280
  identifier: NGPipeAutoEnv1763963343280
  tags: {}
  name: NGPipeAutoEnv1763963343280
  type: PreProduction
