environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766046381718
  identifier: NGPipeAutoEnv1766046381718
  tags: {}
  name: NGPipeAutoEnv1766046381718
  type: PreProduction
