environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763622524351
  identifier: NGPipeAutoEnv1763622524351
  tags: {}
  name: NGPipeAutoEnv1763622524351
  type: PreProduction
