environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765882797862
  identifier: NGPipeAutoEnv1765882797862
  tags: {}
  name: NGPipeAutoEnv1765882797862
  type: PreProduction
