environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767950913590
  identifier: NGPipeAutoNonMainEnvCFOJvfd8fl
  tags: {}
  name: NGPipeAutoNonMainEnvCFOJvfd8fl
  type: PreProduction
