environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769143274678
  identifier: NGPipeAutoNonMainEnviF4MA4eyOa
  tags: {}
  name: NGPipeAutoNonMainEnviF4MA4eyOa
  type: PreProduction
