environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767584829140
  identifier: NGPipeAutoNonMainEnvsB72msY03f
  tags: {}
  name: NGPipeAutoNonMainEnvsB72msY03f
  type: PreProduction
