environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766038597662
  identifier: NGPipeAutoEnv1766038597662
  tags: {}
  name: NGPipeAutoEnv1766038597662
  type: PreProduction
