environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764861514413
  identifier: NGPipeAutoNonMainEnvSJJ4FUvQ6l
  tags: {}
  name: NGPipeAutoNonMainEnvSJJ4FUvQ6l
  type: PreProduction
