environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769633691277
  identifier: NGPipeAutoNonMainEnv5ozshl9jjE
  tags: {}
  name: NGPipeAutoNonMainEnv5ozshl9jjE
  type: PreProduction
