environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764227580309
  identifier: NGPipeAutoNonMainEnv0zzIHrdPSu
  tags: {}
  name: NGPipeAutoNonMainEnv0zzIHrdPSu
  type: PreProduction
