environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764722875050
  identifier: NGPipeAutoEnv1764722875050
  tags: {}
  name: NGPipeAutoEnv1764722875050
  type: PreProduction
