environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763963343280
  identifier: NGPipeAutoNonMainEnvdwrHMu75Kb
  tags: {}
  name: NGPipeAutoNonMainEnvdwrHMu75Kb
  type: PreProduction
