environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764768972602
  identifier: NGPipeAutoEnv1764768972602
  tags: {}
  name: NGPipeAutoEnv1764768972602
  type: PreProduction
