environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767950913590
  identifier: NGPipeAutoEnv1767950913590
  tags: {}
  name: NGPipeAutoEnv1767950913590
  type: PreProduction
