environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764768972602
  identifier: NGPipeAutoNonMainEnviaNjRfLNOT
  tags: {}
  name: NGPipeAutoNonMainEnviaNjRfLNOT
  type: PreProduction
