environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767955341889
  identifier: NGPipeAutoNonMainEnvXwPFK4ObLo
  tags: {}
  name: NGPipeAutoNonMainEnvXwPFK4ObLo
  type: PreProduction
