environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762514360122
  identifier: NGPipeAutoNonMainEnv4KxoJiAJLT
  tags: {}
  name: NGPipeAutoNonMainEnv4KxoJiAJLT
  type: PreProduction
