environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763621575908
  identifier: NGPipeAutoNonMainEnv3z8OA4mbBA
  tags: {}
  name: NGPipeAutoNonMainEnv3z8OA4mbBA
  type: PreProduction
