environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762945284002
  identifier: NGPipeAutoNonMainEnv7l4clNMLnE
  tags: {}
  name: NGPipeAutoNonMainEnv7l4clNMLnE
  type: PreProduction
