environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767872771942
  identifier: NGPipeAutoNonMainEnv2zbEBmrSSV
  tags: {}
  name: NGPipeAutoNonMainEnv2zbEBmrSSV
  type: PreProduction
