environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768043963861
  identifier: NGPipeAutoNonMainEnvhJzCxDdMHJ
  tags: {}
  name: NGPipeAutoNonMainEnvhJzCxDdMHJ
  type: PreProduction
