environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768825213600
  identifier: NGPipeAutoEnv1768825213600
  tags: {}
  name: NGPipeAutoEnv1768825213600
  type: PreProduction
