environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769492372445
  identifier: NGPipeAutoNonMainEnvMLcKJ8R4LF
  tags: {}
  name: NGPipeAutoNonMainEnvMLcKJ8R4LF
  type: PreProduction
