environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763044709557
  identifier: NGPipeAutoNonMainEnvD4tyCN6xpo
  tags: {}
  name: NGPipeAutoNonMainEnvD4tyCN6xpo
  type: PreProduction
