environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762752173244
  identifier: NGPipeAutoNonMainEnvW3Jk8dl8C7
  tags: {}
  name: NGPipeAutoNonMainEnvW3Jk8dl8C7
  type: PreProduction
