environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765518203540
  identifier: NGPipeAutoNonMainEnv6FBovCrAaS
  tags: {}
  name: NGPipeAutoNonMainEnv6FBovCrAaS
  type: PreProduction
