environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768333617487
  identifier: NGPipeAutoEnv1768333617487
  tags: {}
  name: NGPipeAutoEnv1768333617487
  type: PreProduction
