environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769610045306
  identifier: NGPipeAutoEnv1769610045306
  tags: {}
  name: NGPipeAutoEnv1769610045306
  type: PreProduction
