environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1762957052388
  identifier: NGPipeAutoNonMainEnvUOppFVRAj0
  tags: {}
  name: NGPipeAutoNonMainEnvUOppFVRAj0
  type: PreProduction
