environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763044214868
  identifier: NGPipeAutoNonMainEnvYw6Ego6ftB
  tags: {}
  name: NGPipeAutoNonMainEnvYw6Ego6ftB
  type: PreProduction
