environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763357990060
  identifier: NGPipeAutoEnv1763357990060
  tags: {}
  name: NGPipeAutoEnv1763357990060
  type: PreProduction
