environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1769603310829
  identifier: NGPipeAutoNonMainEnvSMj36W13RA
  tags: {}
  name: NGPipeAutoNonMainEnvSMj36W13RA
  type: PreProduction
