environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764351897728
  identifier: NGPipeAutoEnv1764351897728
  tags: {}
  name: NGPipeAutoEnv1764351897728
  type: PreProduction
