environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764722875050
  identifier: NGPipeAutoNonMainEnvyfC3SVD8F8
  tags: {}
  name: NGPipeAutoNonMainEnvyfC3SVD8F8
  type: PreProduction
