environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767757268581
  identifier: NGPipeAutoEnv1767757268581
  tags: {}
  name: NGPipeAutoEnv1767757268581
  type: PreProduction
