environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768042121846
  identifier: NGPipeAutoEnv1768042121846
  tags: {}
  name: NGPipeAutoEnv1768042121846
  type: PreProduction
