environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1763630636731
  identifier: NGPipeAutoNonMainEnv53A9XfFSoC
  tags: {}
  name: NGPipeAutoNonMainEnv53A9XfFSoC
  type: PreProduction
