environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1768380417990
  identifier: NGPipeAutoEnv1768380417990
  tags: {}
  name: NGPipeAutoEnv1768380417990
  type: PreProduction
