environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764145368298
  identifier: NGPipeAutoNonMainEnv91wAnTwe2k
  tags: {}
  name: NGPipeAutoNonMainEnv91wAnTwe2k
  type: PreProduction
