environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1764580568711
  identifier: NGPipeAutoEnv1764580568711
  tags: {}
  name: NGPipeAutoEnv1764580568711
  type: PreProduction
