environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1765518814037
  identifier: NGPipeAutoNonMainEnv35Og8ipkAz
  tags: {}
  name: NGPipeAutoNonMainEnv35Og8ipkAz
  type: PreProduction
