environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1767085695916
  identifier: NGPipeAutoNonMainEnvsOiM2on0Dn
  tags: {}
  name: NGPipeAutoNonMainEnvsOiM2on0Dn
  type: PreProduction
