environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPolicyInfra1766377423520
  identifier: NGPipeAutoNonMainEnv2RFKRFG4UG
  tags: {}
  name: NGPipeAutoNonMainEnv2RFKRFG4UG
  type: PreProduction
